// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzKRWBdoDvU3scNh8DybnjLss2gqL2VRA',
    appId: '1:1014760256752:web:c195f83e6c0ed51b62fe35',
    messagingSenderId: '1014760256752',
    projectId: 'hjgjgyu-6f8f2',
    authDomain: 'hjgjgyu-6f8f2.firebaseapp.com',
    storageBucket: 'hjgjgyu-6f8f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM-j32sbPM9HiTmIKmn03b65a1oOxjGvI',
    appId: '1:1014760256752:android:e130346d1f2b9ee162fe35',
    messagingSenderId: '1014760256752',
    projectId: 'hjgjgyu-6f8f2',
    storageBucket: 'hjgjgyu-6f8f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp95sC94y7hSMLf5bbxk5BOAf_0mIL5-w',
    appId: '1:1014760256752:ios:6a19d12d77d2d0e862fe35',
    messagingSenderId: '1014760256752',
    projectId: 'hjgjgyu-6f8f2',
    storageBucket: 'hjgjgyu-6f8f2.appspot.com',
    iosBundleId: 'com.example.codeday12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp95sC94y7hSMLf5bbxk5BOAf_0mIL5-w',
    appId: '1:1014760256752:ios:50ae243ea234402962fe35',
    messagingSenderId: '1014760256752',
    projectId: 'hjgjgyu-6f8f2',
    storageBucket: 'hjgjgyu-6f8f2.appspot.com',
    iosBundleId: 'com.example.codeday12.RunnerTests',
  );
}
